### PR TITLE
HTML Bars `_registerHelper` fix and Update dependencies

### PR DESCRIPTION
**Pull request by alexdiliberto**
- Update dependencies for latest EmberCLI v0.1.12
 - Fix registerHelper reference (see emberjs/ember.js@ad62ccf)

### CODE REVIEW

**Comment by alexdiliberto** [comment]
@cibernox This should fix https://github.com/cibernox/ember-cli-accounting/issues/7

**Comment by cibernox** [comment]
Thanks!

**Comment by cibernox** [comment]
Published v0.1.1 with this fix

**Comment by alexdiliberto** [comment]
@cibernox Great, thanks!

**Pull request merged**
